// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecyfwluhzjhmnyccnepc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjeWZ3bHVoempobW55Y2NuZXBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMDk3MzUsImV4cCI6MjA2OTc4NTczNX0.etmM0UM5LpyN--S5y7Xj3Sq0ppzkxsNCCexbkQB97ag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});